### ISSUE TITLE
Implement data validation

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#461]
### Description

Please edit this description with new bullets as you think of them:

- [ ] (Outdated?) If GraphAssetData.investable is an array of years, investment_cost should also be an array of equal length. (After multi-year investment is implemented.)
- [ ] #1100
- [x] #1098
- [x] #1101
- [ ] (Outdated?) If a storage asset has a missing is_seasonal, the default is `false` (non-seasonal storage).
- [ ] #1103
- [ ] (Outdated?) If storage inflows are missing, then assign the default = 0
- [ ] #1104
- [x] #437 
- [x] #453 
- [ ] https://github.com/TulipaEnergy/TulipaIO.jl/issues/78
- [x] #1105
- [x] #1109
- [x] #1110
- [x] #1111
- [x] #1112
- [x] #1091
- [ ] Validate `storage_loss_from_stored_energy` stays between 0 and strictly less than 1
- [ ] Consider/fix the interaction of the schemas arg and populate_defaults related to this bug: #1171 
- [ ] Validate or allow missing row in asset-commission
   If an asset exists in `asset` but has no corresponding row in `asset-commission`, the code errors with a cryptic error related to multiplying `Missing` and `JuMP.AffExpr` in the objective. We should either allow the missing row or validate that they don't happen.
   This was uncovered with TulipaBuilder.jl, so steps to reproduced are missing for now.
- [ ] Validate or allow missing row in asset-milestone
   If an asset exists in `asset` but has no corresponding row in `asset-milestone`, the code errors with a cryptic error related to multiplying `Missing` and `JuMP.AffExpr` in the objective. We should either allow the missing row or validate that they don't happen.
   This was uncovered with TulipaBuilder.jl, so steps to reproduced are missing for now.
- [ ] Validate or allow missing row in flow-commission
   If a flow exists in `flow` but has no corresopnding row in `flow-commission`, the code errors with a cryptic error related to converting `Missing` to `Float64` in `model-preparation.jl`. We should either allow the missing row or validate that they don't happen.
   This was uncovered with TulipaBuilder.jl, so steps to reproduced are missing for now.
- [ ] Validate or allow missing row in flow-milestone
   If a flow exists in `flow` but has no corresponding row in `flow-milestone`, the code errors with a cryptic error related to multiplying `Missing` and `JuMP.AffExpr` in the objective. We should either allow the missing row or validate that they don't happen.
   This was uncovered with TulipaBuilder.jl, so steps to reproduced are missing for now.
- [ ] Validate that profiles are between 0 and 1.
- [ ] Validate or allow `investment_cost = 0.0` when `investable`
   If `investment_cost` is 0.0 and the asset is `investable`, the code errors with error related to `NaN` coefficient for `assets_investment[year,asset]` in the objective. We should either allow or validate.
- [ ] Validate that it is not allowed to set `investable=true` if corresponding rows do not appear in `asset_milestone`
   This will create redundant investment variables.

Consider the defaults file Diego has drafted here in function `get_default_values`:
https://github.com/TulipaEnergy/Tulipa-OBZ-CaseStudy/blob/main/functions.jl

- [x] Implement defaults in pipeline
- [x] Document defaults in How-To (probably after Schema, or maybe within Schema?)

**Comment by abelsiqueira** [comment]
We just discussed adding arguments or options to define the use case instead of relying on the existence or not of specific files. I'm not sure how to translate that into a bullet point. I think it still needs some definition of the main use cases.

**Comment by clizbe** [comment]
Yes the discussion was that we should have the user explicitly specify what "features" they're implementing, so that when we perform validation etc we don't have to guess what they want.
For instance, instead of only relying on cost data being present to activate investing, they have to specify when running the model that they want investment, therefore the model checks for certain parameters needed for that feature. Also if they give cost data without specifying they want investment, the model should give feedback that it's ignoring the cost data.

Depending on how many switches there are, this might be a file. But for now we want to have it as arguments to a function call, with defaults for the "regular" way of running and only specifying to change from the default.
