### ISSUE TITLE
Refactor architecture to use Tables (DuckDB)

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#547]
### Description

Given the changes that are happening in the input (ref #289) and that happened in the model, it makes sense to use Tables to store most of data, instead of converting the data into other structures only to convert them back to dataframes in the model.

**We should benchmark and evaluate the changes to make sure they are good ideas.**

### Sub issues

- [x] #544 
- [ ] #115 
- [x] #706
- [ ] #713
- [ ] Change `base_periods` to use DuckDB
- [ ] Change `constraints_partitions` to use DuckDB
- [ ] Change `graph` to a mix of Graph and use DuckDB
- [x] #495
- [ ] #611

**Comment by abelsiqueira** [comment]
We should update or remote this in favour of the discussion happening in #688

**Comment by datejada** [comment]
Closing this issue in favour of Epic #701, which has all the relevant issues that are not finished here (at the moment of closing this issue).
