### ISSUE TITLE
Use tighter formulation for energy storage assets

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#576]
### Description

Implement early work from Maaike's research to improve the energy storage constraints:

https://www.overleaf.com/project/6454fde7fdf7f1c73ceeb2a0

### Sub issues

- [x] Write the equations in this issue using the Tulipa names for variables and constraints (translate Maaike's formulation into Tulipa)
- [x] #640
- [x] #638
- [x] #639
- [x] ~Update the output solution (if needed)~

**Comment by datejada** [comment]
Methods:

- [ ] No binary (with/without inflows current formulation) -> suitable for hydro in cascade, and PHS is feasible charge/discharge at the same time
- [ ] Binary (German's formulation covers cases with/without inflows). It implies that no spillage (as a discharge) can happen simultaneously as charging.
