### ISSUE TITLE
JuMP Model to Output

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#97]
- [x] #35 
- [x] #113
- [x] #114
- [x] Discuss invariance of solutions (something akin to property based testing) (Get back to @suvayu on this) -> #623 
- [ ] #115
- [x] #491 
- [X] ~Create function to filter output~
- [x] #191
- [x] Create the function to convert to ESDL (possibly in Python, possibly part of #88) -> #606 
- [x] #295
- [x] #352

**Comment by abelsiqueira** [comment]
I watched a presentation from Genie Framework (https://genieframework.com) that might be an option for showing the output. The framework can be used to produce dashboards running Julia in the backend.
This is probably overkill, but since I don't know the plans for this part of the project, I will just leave a mention.

**Comment by clizbe** [comment]
This epic is obsolete - continuing in new issues/discussions.
