### ISSUE TITLE
Improve the INPUT workflow

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#974]
The input workflow (raw to model) needs improvements and consolidation. This will take many iterations, but an initial effort should improve the user experience in the short term as our community grows.
This epic focuses mainly on the user-facing features and workflow structure, not what's under the hood (not all TIO should be listed here).

### Phase 1: Clean & Documented (but manual)
- [x] #1039
- [ ] #1087
- [x] #1038
- [ ] #414
  - [x] #996  
- [ ] #997
- [ ] #941
- [ ] How does the user specify that an energy carrier acts like gas/electric?

### Phase 2: A Bit Friendlier
- [ ] #461
- [ ] Create function(s) in TIO to convert UF tables into MF tables
- [ ] https://github.com/TulipaEnergy/TulipaIO.jl/issues/11
- [ ] Add function add_asset(type, args) that requires data but puts it into all the right tables?
- [ ] Add function add_profile?
- [ ] Add function add_flow?

### Phase 3: Clear, Structured, and Smooth
- [x] #685
- [ ] (Probably) Create a wrapper function to convert all tables UF -> MF at once
  - [ ] Once this is done, if it's completely automatic, consider moving ModelFormat inside TEM and just show UserFormat to the user - then conversion happens as pre-processing when they call the model
- [ ] Invent a way to help the user organize/track scenarios
- [ ] https://github.com/TulipaEnergy/TulipaIO.jl/issues/29
- [ ] #875 
- [ ] #686

## Related
- OBZ repo: https://github.com/TulipaEnergy/Tulipa-OBZ-CaseStudy/tree/main
- #975 
- #774
- #635
- #916 
- #700
- #499
- #664
- #68

**Comment by clizbe** [comment]
I've been trying to imagine how an analyst would start from scratch.
Below is a pseudocode of my imagined workflow, using TIO to generate templates that include the columns the user needs.
We could also consider a template repo, but then I think the templates would be set and not dynamic to the user needs.

Not sure if this would all become a nightmare with versioning...

```julia
# Example Workflow (with imaginary parts)

using TulipaIO: TIO
using DuckDB: DDB
using TulipaEnergyModel: TEM

## Create Templates
# - I think it's necessary to first start something in DuckDB?
connection = DBInterface.connect(DuckDB.DB)
# - This function would create tables in DuckDB according to the choices in the analysis_features 'file'
TIO.create_template_tables("analysis_features.csv", connection; table = all)
# - But these tables will be empty except the selection of column names, 
#   so maybe they also need some more input like assets or something

# - This function would be the same as create_template_tables but works on an existing table to add/remove columns
#   Theoretically allowing the analyst to adjust their analysis features on the fly 
TIO.change_feature_columns("analysis_features_v2.csv", connection)

## Import raw data

## Manipulate data into User Format
# - Function to map a column of raw data onto the corresponding UserFormat column 
#   (Maybe this could enable more automatic mapping scripts...)
TIO.map_column(col_raw, col_UF; key_raw, key_UF)
# - Function that fills in defaults - either with auto defaults or specified by user 
TIO.fill_defaults(; defaults_file)
# - Other stuff

## Scenarios?
# - Some way of setting Base scenario and creating Alternatives?
# - For now it seems this is entirely on the user to run the workflow for each scenario...

## Preprocessing?
# - TulipaClustering
# - Time partitions? Created somehow in templates?

## Convert to Model Format
TIO.userformat_to_modelformat(connection)

## Run Model
TEM.run_scenario(connection; optimizer, params...)

```

This idea is taking shape for me, but I need feedback in case it's the wrong direction.
Let's discuss in person in the new year!

**Comment by clizbe** [comment]
If we built a template repo, it could have a few basic files and a Pluto workflow that walks them through...
 1. Fork this repo
 2. Change the `analysis_features` and `defaults` files as necessary
 3. Open the Pluto notebook analysis template and follow the steps

And then maybe the Pluto notebook includes the template workflow above with instructions?

**Comment by abelsiqueira** [comment]
From our meeting on 24/Mar/2025
cc. @clizbe @datejada @suvayu @gnawin 

- We will have a function to **populate tables with default values in TEM** (e.g., `TulipaEnergyModel.populate_with_defaults!(connection)`)
  - This function is not called implicitly anywhere. The user has to use it explicitly to finish preparing the model for TEM (so it is used after TC), or explicitly have a keyword argument that makes it be called (e.g., in `run_scenario`)
- OBZ is the case study to be used as a starting point for the tutorial of end-to-end Tulipa usage.
- The end-to-end Tulipa workflow (diagram being created in #415) is essentially:
  1. `connection = DBInterface.connect(DuckDB.DB)`
  2. Manually load data from source to `connection` (not format is expected)
  3. Manipulate data with DuckDB/TulipaIO. By the end, a _Tulipa User Format_ is expected.
  4. Validate the TUF with `user_data_validation!(connection)` (doesn't exist yet)
  5. More data manipulation can be done
  6. Cluster with TulipaClustering
  7. Manipulate data with DuckDB/TulipaIO. By the end, the _Tulipa Energy Model_ format is expected. (Here the `populate_with_defaults!` function can be used)
  8. TEM starts assuming all data is present. No defaults are set anymore.
- Some helper functions can be created to simplify explicit and implicit parts of the process. In principle, don't assume they exist; have a SQL/DuckDB version of things.

If this is correct, the following action points can be created as issues (or already have issues):

- [ ] Create a function to populate TEM tables with defaults available in the schema.
- [ ] Define the Tulipa User Format.
    For instance, using the JSON schema.
- [ ] Implement `user_data_validation!(connection)`. Store it in the same place as the Tulipa User Format
- [ ] Have an end-to-end test of the pipeline (possibly extending `test-pipeline.jl` with OBZ data)
- [ ] Update the documentation with an end-to-end tutorial (possibly the OBZ pipeline)

**Comment by suvayu** [comment]
> Create a function to populate TEM tables with defaults available in the schema.

I was thinking about an _efficient_ implementation for this, and I'm not sure that this can be decoupled from creating the "ready for TEM" tables.  E.g look at this from the case study PR (TulipaEnergy/Tulipa-OBZ-CaseStudy#20):

https://github.com/TulipaEnergy/Tulipa-OBZ-CaseStudy/blob/d1be7da5b1762ee749747958ae6cadf35ae60c04/utils/functions.jl#L69-L72

I guess now I've finally found a concrete reason for my "uneasy feeling".

**Comment by abelsiqueira** [comment]
I will have to decipher to judge, but I don't think efficiency is the main concern for this part. So even if it is slow, as long as it is not absurdly slow, it should be fine. The only concern related to speed in this part are profiles. Partitions are still "rolled" here and the other files should be small, even in the big case.
And maybe those lines are indeed the function, or at least the initial version of it.

This opinion might change after I actually understand the pipeline/workflow/OBZ side of things better.
